### ISSUE TITLE
duble - od fanboyi

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#107]
Znalazłem trochę zbędnych dubli (to samo co u fanboyi)

Polskie Filtry Społecznościowe | Fanboy’s Social
--- | --- 
`pl###article-sidebar-action-facebook` | `###article-sidebar-action-facebook`
`pl###facebook-popup` | `###facebook-popup`
`pl###facebook-win` | `###facebook-win`
`pl###facebookBox` | `###facebookBox`
`pl###facebookFans` | `###facebookFans`
`pl###facebookWindow` | `###facebookWindow`
`pl###facebook_begen` | `###facebook_begen`
`pl###facebook_page_block` | `###facebook_page_block`
`pl###facebook_page_block_lenta` | `###facebook_page_block_lenta`
`pl###facebook_reader_wrapper` | `###facebook_reader_wrapper`
`pl###fb_like_pop` | `###fb_like_pop`
`pl###fblikepop_ads` | `###fblikepop_ads`
`pl###iscfbbblikewidget` | `###iscfbbblikewidget`
`pl###koddostu_facebook_begen` | `###koddostu_facebook_begen`
`pl###like-btn` | `###like-btn`
`pl###like_popup` | `###like_popup`
`pl###likebox` | `###likebox`
`pl##.Facebook` | `##.Facebook`
`pl##.Instagram` | `##.Instagram`
`pl##.Tfacebook` | `##.Tfacebook`
`pl##.Twitter` | `##.Twitter`
`pl##.addthis_button_twitter` | `##.addthis_button_twitter`
`pl##.article__likes` | `##.article__likes`
`pl##.article__likes-title` | `##.article__likes-title`
`pl##.aspexifblikebox` | `##.aspexifblikebox`
`pl##.b_like` | `##.b_like`
`pl##.comments__likes` | `##.comments__likes`
`pl##.facebook-bn_site-overlay` | `##.facebook-bn_site-overlay`
`pl##.facebook-plain-control` | `##.facebook-plain-control`
`pl##.facebook-popup` | `##.facebook-popup`
`pl##.facebook-solid-control` | `##.facebook-solid-control`
`pl##.facebook-toolbar` | `##.facebook-toolbar`
`pl##.facebookIco` | `##.facebookIco`
`pl##.facebookLikeBoxSmall` | `##.facebookLikeBoxSmall`
`pl##.facebookThis` | `##.facebookThis`
`pl##.facebook_like` | `##.facebook_like`
`pl##.facebook_like_pane` | `##.facebook_like_pane`
`pl##.facebookactivity` | `##.facebookactivity`
`pl##.facebooks` | `##.facebooks`
`pl##.fb-widget` | `##.fb-widget`
`pl##.fbButton` | `##.fbButton`
`pl##.fb_icon` | `##.fb_icon`
`pl##.fb_like_wrap` | `##.fb_like_wrap`
`pl##.fblikebtn` | `##.fblikebtn`
`pl##.fixed-like-box` | `##.fixed-like-box`
`pl##.floatinglikebox` | `##.floatinglikebox`
`pl##.ico-fb` | `##.ico-fb`
`pl##.ico-instagram` | `##.ico-instagram`
`pl##.ico-pinterest` | `##.ico-pinterest`
`pl##.image_icon_facebook_left` | `##.image_icon_facebook_left`
`pl##.in_icon` | `##.in_icon`
`pl##.jj_sl_facebook` | `##.jj_sl_facebook`
`pl##.jj_sl_twitter` | `##.jj_sl_twitter`
`pl##.jj_sl_youtube` | `##.jj_sl_youtube`
`pl##.like-b` | `##.like-b`
`pl##.like-block` | `##.like-block`
`pl##.like-box` | `##.like-box`
`pl##.like-holder` | `##.like-holder`
`pl##.like-layer` | `##.like-layer`
`pl##.like_block_rendered` | `##.like_block_rendered`
`pl##.like_button` | `##.like_button`
`pl##.like_buttons` | `##.like_buttons`
`pl##.like_wall` | `##.like_wall`
`pl##.like_widget` | `##.like_widget`
`pl##.likeboxes` | `##.likeboxes`
`pl##.likebutton` | `##.likebutton`
`pl##.likely__widget` | `##.likely__widget`
`pl##.likes-block` | `##.likes-block`
`pl##.likes-block_left` | `##.likes-block_left`
`pl##.link-facebook` | `##.link-facebook`
`pl##.mobile-facebook` | `##.mobile-facebook`
`pl##.momizat-facebook` | `##.momizat-facebook`
`pl##.r-likes-wrapper` | `##.r-likes-wrapper`
`pl##.radium-builder-widget-facebook-like-box` | `##.radium-builder-widget-facebook-like-box`
`pl##.share-facebook` | `##.share-facebook`
`pl##.share-fb` | `##.share-fb`
`pl##.share-google-plus-1` | `##.share-google-plus-1`
`pl##.share-linkedin` | `##.share-linkedin`
`pl##.share-pin` | `##.share-pin`
`pl##.share-pinterest` | `##.share-pinterest`
`pl##.share-reddit` | `##.share-reddit`
`pl##.share-tumblr` | `##.share-tumblr`
`pl##.share-tw` | `##.share-tw`
`pl##.share-twitter` | `##.share-twitter`
`pl##.soc_tw` | `##.soc_tw`
`pl##.social-fb` | `##.social-fb`
`pl##.social-gp` | `##.social-gp`
`pl##.social-tw` | `##.social-tw`
`pl##.social_widgets` | `##.social_widgets`
`pl##.socials-bar` | `##.socials-bar`
`pl##.toolbar-facebook` | `##.toolbar-facebook`
`pl##.toolbar-linkedin` | `##.toolbar-linkedin`
`pl##.toolbar-twitter` | `##.toolbar-twitter`
`pl##.tw_icon` | `##.tw_icon`
`pl##.user_activity_like_block` | `##.user_activity_like_block`
`pl##.widget_bimber_widget_facebook_page` | `##.widget_bimber_widget_facebook_page`
`pl##.widget_easy_facebook_page_plugin` | `##.widget_easy_facebook_page_plugin`
`pl##.widget_likebox` | `##.widget_likebox`

**Comment by krystian3w** [comment]
Pytanie ile polskich ma `@@*$generichide`.

**Comment by krystian3w** [comment]
Generator tabel:

https://www.tablesgenerator.com/markdown_tables

I przypominam, że polska ortografia wymaga nie robienia spacji po "(" i przed ")" i podobnie z przecinkami, średnikami, kropkami.

**Comment by krystian3w** [comment]
`pl###facebook-popup`

duplikowane pod EI?

**Comment by krystian3w** [comment]
Myślę, że szybciej wyłapiemy nowe niezbędne `@@*$ghide` po usunięciu schronu.
