### ISSUE TITLE
strefapd.pl

### ISSUE THREAD

**Issue by hawkeye116477** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#109]
![2021-09-22_17-43](https://user-images.githubusercontent.com/19818572/134376630-80d25391-a5aa-4c0d-bd67-06f04f50e203.png)

**Comment by krystian3w** [comment]
`strefapd.pl#?#body > div.elementor-popup-modal:-abp-has(a[href*="/cookies/"])`

Jak miga, to może siedzi to w osobnym pliku/żądaniu sieciowym (xhr/ajax).

**Comment by krystian3w** [comment]
AdamWr zatwierdza.
