### ISSUE TITLE
Pytanie

### ISSUE THREAD

**Issue by gargaamel** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#14]
@krystian3w @hawkeye116477 

Jako, że ten pedał bez honoru i zasad @MajkiIT, dał mi przed chwilą bana, bo mu zwróciłem uwagę żeby nie był taki upośledzony i poprawnie etykietował moje zgłoszenia, a nie leciał sobie w kulki, to czy da radę tu robić zgłoszenia? No bo ku..wa pomagam w h..uj i chcę jeszcze pomóc w wybiciu tych rodo-ciasteczek, ale u tamtego cwela nie da rady, on zawsze sprowokuje i zaczepi, żeby mnie wkurzyć, a potem daje po cichu bana, typowy cwel nadający się do obciągania laski, poza tym kasuje/edytuje i cenzuruje niewygodne dla niego posty, ma coś z głową, nie żebym się żalił, tylko wyjaśniam sytuację i pytam czy da radę, więc chłopaki, mam nadzieję, że nie jesteście tacy jak on, macie klasę i jakoś mi umożliwicie kontrybucję, a jeśli nie to trudno, hu..a na was wszystkich położę i na te całe filtry.

**Comment by krystian3w** [comment]
<p align="center"><i>Ja mam uprawnienia do zgłoszeń, pr, commitów.</i></p>

<p align="center">Bardziej to w gestii @blocker999  i @hawkeye116477.</p>

**Comment by gargaamel** [comment]
Spoko, rozumiem.

**Comment by hawkeye116477** [comment]
@gargaamel Obrażasz ludzi, a potem dziwisz się skąd te banany...
