### ISSUE TITLE
Dev w nazwie filtrów

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#15]
Dałoby się dorobić do skryptu by był napis że to wersja dev, niby w Firefox mogę do sobie jakoś dokleić w pliku `userContent.css`, ale na Operze od Chromium 61 niestety nie.

**Comment by hawkeye116477** [comment]
@krystian3w W plikach templatowych możesz to dodać.

**Comment by hawkeye116477** [comment]
Można dopisać do Version Dev, ale jeżeli ma być w nazwie filtrów, to już trochę większa zabawa. Najlepiej byłoby chyba zrobić tak, żeby dopisać Dev do title w templacie, a w skrypcie do robienia RTM dorobić usuwanie słowa Dev.

**Comment by krystian3w** [comment]
A czyli znowu `sed` pewnie
