### ISSUE TITLE
domain.xyz##.social

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#18]
<pre><code>alesoczewki.com,...,wspanialewesele.com.pl##<b>.social</b>  (48)
		 
		bananki.pl###gplus, <b>.social</b>
		bankobranie.blogspot.com###sideSocial &gt; <b>.social</b> &gt; li:nth-child(-n+4), #logoSocial &gt; <b>.social</b> &gt; li:nth-child(-n+4)
		bankrutemjestem.pl,intercyza-blog.pl,jakzwolnicpracownika.pl,latam-dronem.pl,naratunekkreatywnym.pl,patrykzbroja.pl,pozewzfaktury.pl,prawnikdlakonsumenta.pl,prawo-autorskie-blog.pl,prawonaplacubudowy.pl,przedsiebiorcawsadzie.pl,wdrodzedokancelarii.pl,zarzadwspolcezoo.pl##<b>.social</b> &gt; a[class]:not([href*="/feed/"])
		breakplan.pl##nav.bottom:nth-of-type(2), <b>.social</b>
		certyficate.it##.message<b>.social</b>
		chemik-police.com##.twitter, #footer &gt; <b>.social</b>, .youtube-cta
		columbusenergy.pl##.menu-second &gt; .margin &gt; <b>.social</b>, .clear-fix.row, .dark-box:nth-of-type(1)
		doba.pl###panel, <b>.social</b>
		dobreprogramy.pl##div.col:nth-of-type(3) &gt; .list &gt; li.list__item:nth-child(n+2), .author-social-links, .dl-social, .content.float-right &gt; <b>.social</b>, .float-right<b>.social</b>, .tools-social, <b>.social</b>__group_share, <b>.social</b>__group_like &gt; <b>.social</b>__item, #phContent_page_content <b>.social</b>__group_like, [class^="StyledShareProviderButtons"]
		dobrzemieszkaj.pl##<b>.social</b>, .right.box-6 &gt; .desc
		echo24.tv##.hide-mobile<b>.social</b>
		ekologiczny.pl###widget_shop1, <b>.social</b>
		ekspert.ceneo.pl##<b>.social</b>.widget
		emt-systems.pl##.top-main &gt; li:nth-of-type(13), <b>.social</b>.footer-menu
		eska.tv##<b>.social</b>.box
		eurobank.pl##.last.f-div &gt; .bold, <b>.social</b>
		fly.pl##li<b>.social</b>.hidden-sm.hidden-xs:nth-child(-n+4)
		gdynia.pl##.widget-text-block &gt; div &gt; <b>.social</b> &gt; li:nth-child(-n+5)
		guzik.konin.pl##.widget_text<b>.social</b>.widget-bottom.uk-panel-box.uk-panel
		intellect.pl##<b>.social</b>, .right &gt; .head
		irobot.pl##li.medialink, <b>.social</b>.futerul
		kingsong.pl##<b>.social</b> &gt; a:nth-of-type(n+3):nth-of-type(-n+4)
		lowicz24.eu##li<b>.social</b>
		lublin24.pl##<b>.social</b> &gt; [href="https://www.facebook.com/lublin24/"], <b>.social</b> &gt; [href="#"]
		m.se.pl##<b>.social</b>.row
		media-tech.eu###widget_shop4, <b>.social</b>
		multimedia.pl##.columns<b>.social</b>
		nieznany-numer.pl##.titleRwd:nth-of-type(5), <b>.social</b>
		nportal.no##<b>.social</b>, <b>.social</b>-right-column, .blue.bar:nth-of-type(4)
		olgasmile.com##<b>.social</b> &gt; li:nth-child(-n+3)
		polscygracze.pl##.bb-post-share-box, .share-toggle, <b>.social</b><b>.social</b>-footer &gt; ul &gt; li &gt; .bb-ui-icon-facebook
		polskaekologia.org###object &gt; <b>.social</b>, #block-block-28
		polskaizbabranzypogrzebowej.pl##<b>.social</b>.column--1-4
		prostozmostu.pl##.at_flat_counter, <b>.social</b>
		przedawnione.pl##<b>.social</b> &gt; .s_link
		pzlsedziszow.pl##div.container:nth-of-type(4) &gt; .row &gt; div.col-md-6.col-sm-12:nth-of-type(2), #footer-contact &gt; <b>.social</b>
		queer.pl##<b>.social</b> &gt; .label
		tatromaniak.pl##.btn-join, div:nth-of-type(2) &gt; [href="https://spolecznosc.tatromaniak.pl/"], .text--light.CTA, <b>.social</b>, .feed
		tekstowo.pl##.teledysk-right &gt; <b>.social</b> &gt; .link-sl
		telko.in##<b>.social</b> li:nth-of-type(2)
		tenit.com.pl##li<b>.social</b>:nth-of-type(n+1)
		traftu.pl##<b>.social</b> &gt; span
		tvn24bis.pl##.title-wrapper &gt; <b>.social</b>, .fbClassicBox, .forum-header-box &gt; h3
		tygodnikbydgoski.pl##<b>.social</b>:nth-of-type(5), <b>.social</b>:nth-of-type(6), <b>.social</b>:nth-of-type(7)
		wnp.pl###menu1 &gt; <b>.social</b>
		wnp.pl##<b>.social</b> &gt; li:nth-child(-n+4):nth-child(n+2)
		www.tytan.pl##.top_part &gt; <b>.social</b>
		wydawnictwoliterackie.pl##.header_top_social, <b>.social</b>
</code></pre>

chyba że to za duży kawałek by jakoś reorganizować.

**Comment by hawkeye116477** [comment]
Jak chcesz, to się tym zajmuj, ale pewnie zaraz gomoku wrzuci kolejnego questa :smile:.

**Comment by krystian3w** [comment]
Na pewno się nie nadaje na generyk, ale mogę połączyć te co mają `, .social` bez dodaktów, że coś konkretnego bo za dużo tej klasy wszędzie.
