### ISSUE TITLE
Usuwanie klas/stylów i innych jak są samodzielne na stronie?

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#20]
`pl##+js(remove-attr.js, class|style, body[class="modal-open"][style="padding-right: 17px;"])`

`pl##+js(remove-attr.js, class|style, html[class="modal-open"][style="padding-right: 17px;"])`

---

~~Zakładając że to na większości zadziała.~~

Uniknąć można np. poziomego uswaka gdy żadna wartość dla `overflow` go nie usuwa i trzeba to olać lub resetować na `overflow-y`.

**Comment by hawkeye116477** [comment]
Raczej takich ogólnych na wszystkie pl to bym nie robił.

**Comment by krystian3w** [comment]
Jak na razie zauważyłem, to w Firefox to nie chce niestety działać, CSP?

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/12332 - tu pomaga.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/12342

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/12478 - tu też pomaga? Ale wiadomo CSS awaryjnie też.

**Comment by krystian3w** [comment]
```css
body[class="modal-open"][style^="padding-right: "][style$=" px;"]:not([style*="; "]) 
```

Niby zakers pikseli może skakać do 16 czy 18.
