### ISSUE TITLE
siecportali.pl/realizacje

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#24]
~75 domen

```
http://siecportali.pl/realizacje
```

na części migające rodo od @blocker999 i czasem pasek cookies np. `nizanskie.info`

**Comment by hawkeye116477** [comment]
Dobra tam, niech miga, niech sobie poczytają, dowiedzą się o prywatności :smiley:

**Comment by krystian3w** [comment]
Za szybko by to przeczytać nawet po skosie od góry do dołu.
