### ISSUE TITLE
bez html uszkodzony?

### ISSUE THREAD

**Issue by krystian3w** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#27]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/blob/2cb92a6b80d251d5c27e619ba4c321a3131ebddb/sections/adblock_cookies/uBO_AG/komunikaty_bez_html.txt#L2

takie `muzyczne radio` tam nie ma filtra na komunikat, scroll odblokowali?

**Comment by hawkeye116477** [comment]
@krystian3w Nieładnie...
