### ISSUE TITLE
kbw.gov.pl

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#30]
https://pila.kbw.gov.pl/337_Informacje

![s](https://i.imgur.com/AXmU6nx.png)

![g](https://i.imgur.com/DieFEwC.png)

**Comment by hawkeye116477** [comment]
Ok, teraz też widzę, ale na Waterfoksie. Na Vivaldim tego nie mam, dziwne :smiley:

**Comment by krystian3w** [comment]
Ja mam na `69` nie tylko na `56`.

**Comment by hawkeye116477** [comment]
Co taki staroć? Ja mam Vivaldi oparte na Chromium 77 :stuck_out_tongue:

**Comment by FadeMind** [comment]
Information                            | Value
---                                    | ---
Operating system:                      | Windows 10 1909 x64 (lastest)
Browser:                               | Firefox Quantum Stable x64 (lastest)
Browser:                               | Google Chrome Stable x64 (lastest)
AdGuard version:                       | **7.2.xxxx NIGHTLY** 
Stealth Mode:					       | disabled
Chrome Extension: | [Polska Ciasteczkowa Zgoda](https://chrome.google.com/webstore/detail/polish-cookie-consent/bniijddcmabghibaojbkbnngbedopbno) 


| **=== FILTERS ENABLED ===**
|---|
| **SECTION :: Other**
| CoinBlockerLists by ZeroDot1
| **SECTION :: Ads**
| Adguard Base Filter 
| Peter Lowe's List
| **SECTION :: Privacy**
| Adguard Spy Filter
| **SECTION :: Social**
| Adguard Social Filter
| **SECTION :: Annoyances**
| Adguard Annoyances
| I don't care about cookies
| Fanboy's Cookiemonster
| **SECTION :: Security**
| Malware Domains
| Spam404
| **SECTION :: Customs**
| AlleBlock
| KAD - Przekręty
| Official Polish filters for AdBlock, uBlock Origin & AdGuard
| Polish Anti Adblock Filters
| Polskie Filtry Elementów Irytujących
| Polskie Filtry Społecznościowe

**Comment by krystian3w** [comment]
Firefox dopiero próbuje dogonić: https://hacks.mozilla.org/2019/09/moving-firefox-to-a-faster-4-week-release-cycle/ i może za 2 lata przegoni Chromium.

**Comment by hawkeye116477** [comment]
@krystian3w Ah, ty mówiłeś o FF, ja myślałem, że Chrome/Chromium 69.

**Comment by FadeMind** [comment]
@krystian3w rozszerz zasięg na `kbw.gov.pl`
![s](https://i.imgur.com/kJaca4E.png)

**Comment by krystian3w** [comment]
OK.

**Comment by krystian3w** [comment]
W polski filtrach irytujących do jakiś 3 godzin powinno być widoczne, buttony social muszą czekać aż ktoś zaakceptuje PR z ~4 aktualizacjami i od tego momentu ~3 godziny.

**Comment by krystian3w** [comment]
https://github.com/MajkiIT/polish-ads-filter/issues/16730
