### ISSUE TITLE
polityka.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#37]
Proponuje, usunąć 
`www.polityka.pl##.hiddenOnMobile.header-share-links, #md-footer_social, .md-sharethis-toolbox-floatingbutton_fb, .wykopTo.md-sharethis-toolbox-floatingbutton_wykop`
w zamian dodać
 `polityka.pl##.cg_footer_share_icons`

**Comment by hawkeye116477** [comment]
`.cg_footer_share_icons`

To już jest na liście, natomiast `www.polityka.pl##.hiddenOnMobile.header-share-links, #md-footer_social, .md-sharethis-toolbox-floatingbutton_fb, .wykopTo.md-sharethis-toolbox-floatingbutton_wykop` to chyba w ogóle już nie działa, co @krystian3w?

**Comment by krystian3w** [comment]
Trzeba sprawdzić mobilną wersje może kiepskie RWD.

**Comment by krystian3w** [comment]
Dobra, to jest sprzed prawie 2 lat:

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/6c0bcb0f694ece29d8fbadae1444865801bca2d7#diff-7d75ec8c9fdd628fa1e1bd503449fc13R1437

Raczej na 99% już zmienili kompletnie layout.
