### ISSUE TITLE
filtr *##.twitter

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#39]
```
biore.to,channel9.msdn.com,chemik-police.com,debica24.eu,domeny.pl,dzieje.pl,fakt.pl,gremont.pl,ksiegarnia.karta.org.pl,sejm.gov.pl,siatka.org,tvn24bis.pl,zw.lt##.twitter
```
- raczej do usunięcia, za dużo blokuje a poza tym Fanboye to blokują

**Comment by krystian3w** [comment]
Raczej znowu do sprawdzenia, a jak uruchomili globalny generyk to trzeba znów zobaczyć co z `naekranie.pl` (tweety).

**Comment by hawkeye116477** [comment]
Na biore.to nie ma takiego elementu, natomiast np `chemik-police.com` wymaga tej reguły, Fanboy nie ukrywa.

**Comment by hawkeye116477** [comment]
Na `biore.to`, `dzieje.pl`, `ksiegarnia.karta.org.pl`, `zw.lt` nie ma takiego elementu, natomiast reszta wymaga takiej reguły. Pytanie jest, gdzie tam za dużo blokuje, bo ja nie zauważyłem?

**Comment by krystian3w** [comment]
Może jako generyk za dużo blokował...

**Comment by blocker999** [comment]
Już sam niewiem, jak dlamnie to może być nawet ogólna ale decyzja należy do Was.

**Comment by krystian3w** [comment]
Ogólna to była i wyleciała po uszkadzaniu `naekranie.pl`.

Pytanie czy te około 5 domen jest za mocno pocięte jednym filtrem - np. nie widzisz żadnych osadzonych tweetów a takich lista ma nie wycinać.
