### ISSUE TITLE
danfoss.pl

### ISSUE THREAD

**Issue by klakieer** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#4]
polityka / ciasteczka

![ss1](https://user-images.githubusercontent.com/44292328/47265250-603e4500-d525-11e8-83be-829d0206f02f.png)

**Comment by krystian3w** [comment]
Linków ze stopki nie wycinamy (jak i takich statycznych gdzieś wstawionych najczęściej też), to najłagodniejsza opcja informowania o ciasteczkach i polityce prywatności.
