### ISSUE TITLE
atrium-*.pl

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#40]
```
atrium-felicity.pl,atrium-koszalin.pl##.ico-foursquare.ico, .ico-new-instagram.ico-new, #header_link_fb_mobile, #header_link_4sq_mobile, #header_link_instagram_mobile
```

 - raczej do usunięcia, Fanboye to blokują

**Comment by krystian3w** [comment]
Test robisz wyłączając polski?

**Comment by blocker999** [comment]
Tak mam wyłączone polskie sociale, być może coś przeoczyłem, aha mam jeszcze kilka podejrzeń (10-15) pytam bo nieche was hamsko zawalać robotą, wrzucać czy nie?

**Comment by krystian3w** [comment]
Jak dla mnie możesz wrzucić jak nie będzie tego 30 dziennie (24h x 7d), to można robić po kilka na dzień.

Przy jakiś stonogach i tak pewnie trzeba będzie dłużej pogłówkować czy się coś da zrobić.

**Comment by hawkeye116477** [comment]
Nawet tych stron już nie ma, tzn. przynajmniej pod starą nazwą.
