### ISSUE TITLE
###bossbyte_slide

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#44]
```
adwokatura.katowice.pl,artgos.pl,bazarek.net.pl,buziak.nl,buziak.pl,enigmatech.eu,exponet.pl,fitandyummy.pl,gran.olsztyn.pl,kompilo.com,latarki.pl,spozywcza.lodz.pl,talbud.pl,technoo1.free.fr,turystykamlodziezowa.pl,wesoly-przedszkolak.pl,wicanders.pl###bossbyte_slide
```

**Comment by krystian3w** [comment]
zbyt ogólna nazwa "widżetu"?

**Comment by hawkeye116477** [comment]
Niby trochę zbyt ogólna, ale póki co nie znalazłem takiej strony, by mieli coś innego niż FB pod tym id, a jest ponad 200 stron z tym widżetem => https://www.nerdydata.com/reports/id-bossbyte_slide/38b6e9cc-c1ff-4660-b990-19ba89502f94.
