### ISSUE TITLE
##.social-conteiner

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#46]
```
fightershop.pl,modele-centrum.pl,motocombo.pl,nbielizna.pl,pcoutlet.pl,plumeria.sklep.pl,sklep-muzyczny.com.pl,soleibabe.pl,ubraniak.pl,vanitysklep.pl,wellsamed.pl##.social-conteiner
```

**Comment by krystian3w** [comment]
Można by pomyśleć co ogólnie tam mają, wtedy z 5/6 domen zniknie z stonogi / gąsienicy #18 (`##.social`).

**Comment by hawkeye116477** [comment]
To już Fanboy ma https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/issues/46#issue-595861008

**Comment by krystian3w** [comment]
W gąsienicy jest 5/6 sklepów, usuńmy je.

**Comment by hawkeye116477** [comment]
Ale to już jest osobna sprawa, zrób nowe zgłoszenie :stuck_out_tongue:

**Comment by krystian3w** [comment]
Problem jakby te 5 sklepów miały generichide lub jakiś glitch z wydajnością `##.social-conteiner` fanboya.

**Comment by krystian3w** [comment]
I na moje fanboy nie uruchomił globalnie blokady:

> ![obraz](https://user-images.githubusercontent.com/35370833/78898160-a23dac80-7a73-11ea-88a1-bb9d3dbdc47f.png)

**Comment by hawkeye116477** [comment]
Ah, jest u niego podobna reguła, ale nie ta sama, mój błąd.

**Comment by krystian3w** [comment]
Mnie też się wydaje, że czasem social-conteiner może mieć logo sklepu (copyright niby z prawej w osobnym `div-ie`), fanboy takich nie odblokowuje.

**Comment by hawkeye116477** [comment]
Teraz powinno być ok, jeden zostawiłem, bo nagłówek inaczej zostaje.
