### ISSUE TITLE
pl###wysuwane

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#47]
```
ckpodgorza.pl,consil.com.pl,dachyonline.pl,darmowe-torrenty.net,europedirect-katowice.pl,evacalor.pl,expander.net.pl,fabrykazabawek.eu,faxtel.com.pl,gckis.trzebnica.pl,hifiphilosophy.com,hotelpiotr-gorce.pl,madziafashion.blogspot.com,mgok-wielen.pl,mosir.org.pl,mtbiznes.pl,musicinfo.pl,naklejkolandia.pl,narzedziadiamentowe.com,poltext.pl,prawo-porady.pl,primadent.com.pl,pzszerm.pl,rajsmakosza.pl,schronisko.olsztyn.pl,skiny.pl,spartanshop.pl,tylkobalonem.pl,wader.toys,www.nmfmk.pl###wysuwane
```

Proponuje tu dać ogólną `pl###wysuwane`

**Comment by hawkeye116477** [comment]
Wysuwane mogą być różne elementy, niektóre są w EI, więc raczej odpada.

**Comment by blocker999** [comment]
No w sumie masz racje a nie idzie tego jakoś ograniczyć tylko do sociali albo dać inną regułe ogólną ?

**Comment by hawkeye116477** [comment]
Niestety nie da rady.

**Comment by krystian3w** [comment]
Można robiąc z tego ułoma:

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/blob/721d43695a958bf9a7e69b39ba01294182cc2e07/sections/adblock_social_list/ogolne_ukrywajace.txt#L236-L238

Ale kij wie czy leń podmieni tylko ikonkę z google plus na Aledrogo... lub jakieś tanie "Opinioneo".

**Comment by krystian3w** [comment]
No chyba że wysuwane do PASS (RSS) i tam rozpatrywać reklamacje blokady super ważnej funkcji np. latającego wysuwanego schowka / koszyka.

**Comment by hawkeye116477** [comment]
@krystian3w Nie.
Raczej kosmetycznymi zbytnio nie wskóramy. Do niektórych zdaje się, że można zastosować sieciową `/fbpodklad.png`, ale nie wiem czy ona też nie narobi szkód, bo może ktoś wpadnie na pomysł, by tak nazwać co innego.

**Comment by krystian3w** [comment]
A nie lata biała plansza jak się przy krawędzi macha, Fanboy nie sprawdza krawędzi a Gargul i Blocker narzekają jak coś z krawędzi się wysuwa a buttona nie widać.

**Comment by hawkeye116477** [comment]
@krystian3w No lata, ale wtedy też niby jest na to rada, dodatkowo jeszcze można dać `ckpodgorza.pl###wysuwane iframe[src*="facebook"]`.

**Comment by hawkeye116477** [comment]
Ok, zrobione na tyle ile się dało.
