### ISSUE TITLE
##.kac-sm-panel

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#48]
```
biurorachunkowe-swidnica.com.pl,emkatrans.com.pl,hurtowniachemiczna.com,jampol.eu,komlogo.pl,krainazabawy.pl,materialybudowlanekrokowa.pl,mckenzie.pl,meblesosnowe.eu,mebloteka.eu,oknajachimczak.com,petrusserwis.pl,sklep.akces-plexi.pl,sklep.audiofil.eu,sklep.hart-metale.pl,uzdrowiska-klodzkie.pl,uzdrowiska-pgu.pl,www.hanbud.com.pl##.kac-sm-panel
```

**Comment by krystian3w** [comment]
#47 - czyli problematyczne jak wcisną "Aledrogo" / "Opionioneo".

**Comment by krystian3w** [comment]
Można przejrzeć inne skacowane wycinające tylko FB/Insta/Twitter.

**Comment by hawkeye116477** [comment]
Tutaj raczej nie ma co kombinować, chyba jedynie G+ dało by się bezpiecznie jako generyk schować, tyle tylko, że G+ już nie ma, więc raczej nie ma co świrować...

**Comment by hawkeye116477** [comment]
Ok, quest ukończony, zostawiłem jedynie te biuro, bo nie wiem co z nim, na razie niby nie działa.
