### ISSUE TITLE
farmacja.pl

### ISSUE THREAD

**Issue by klakieer** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#5]
rodo / polityka / ciasteczka

![ss1](https://user-images.githubusercontent.com/44292328/47265262-9a0f4b80-d525-11e8-9c94-9b3041606656.png)

**Comment by krystian3w** [comment]
Nie da się zaakceptować jako ktoś inny niż lekarz / farmaceuta / zaopatrzeniowiec leczniczy.
