### ISSUE TITLE
interauto.krakow.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#55]
![capture_198_08-06-2020_15-35-16](https://user-images.githubusercontent.com/63287518/84036578-a9166c00-a99d-11ea-97b4-91ba90a47513.gif)

**Comment by krystian3w** [comment]
Dziwne...

coś łapie a jednak inny układ elementów:

```
##div[class]:not([id]) > aside.type-10.widget, section[class]:not([id]) > aside.type-10.widget, div[class]:not([id]) > div[id].type-10.widget > aside.type-10.widget
```

**Comment by gargul2** [comment]
Dalej / znowu jest ten komunikat ciasteczkowy.
