### ISSUE TITLE
Dziwny zbieg okoliczności

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#60]
### Typ elementu/problemu
- [] Wyskakujące okienko (popup)
- [x] Komunikat dot. ciasteczek/polityki prywatności/RODO
- [] Element społecznościowy
- [] Błąd
- [x] Pytanie
- [] Ulepszenie
- [] Redundancja

Zauważyłem przed chwilą, że 2 z 3 ostatnich moich zgłoszeń ciasteczkowych na tym repo zostało także naprawionych w I don't care about cookies, obydwa naprawione zgłoszenia są naprawione filtrami specyficznymi w obydwu listach, więc nie naprawił ich przypadkowo jakiś generyk z Kiboke, tylko zostały świadomie naprawione u Kiboke, jeden z filtrów jest taki sam jak w POL liście, a drugi jest podobny, trochę zmodyfikowany. Zwykły zbieg okoliczności czy ktoś podgląda / podkrada zgłoszenia z tego repo do Kiboke, lub może to nawet sam Kiboke? Może przez to jest [TYLE DUPLIKATÓW](https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/issues/52).

**Comment by hawkeye116477** [comment]
Jeżeli chodzi o wyjątki, to sami go czasem wołamy. A jeśli nie, no to podejrzana sprawa....
