### ISSUE TITLE
inzynierbudownictwa.pl

### ISSUE THREAD

**Issue by gargul2** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#76]
![Nagrywaj_2020_06_25_15_06_19_212](https://user-images.githubusercontent.com/63287518/85725514-79819680-b6f5-11ea-89bf-aa6c77ce2c6a.gif)

**Comment by hawkeye116477** [comment]
@krystian3w Co tu nieprawidłowe? Ikonki YT zwykle chyba ukrywaliśmy.

**Comment by krystian3w** [comment]
Za dużo i nie socialem...

**Comment by krystian3w** [comment]
ten z EI za mocny: `inzynierbudownictwa.pl##.slideLeftItem` najpewniej.

**Comment by hawkeye116477** [comment]
Czyli to @blocker999 narozrabiał.
