### ISSUE TITLE
aptekagemini.pl

### ISSUE THREAD

**Issue by Barticf** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#87]
Pusta strona gdy włączony jest filtr Polskie Filtry Elementów Irytujących [aptekagemini.pl #17176](https://github.com/MajkiIT/polish-ads-filter/issues/17176)

**Comment by krystian3w** [comment]
Zalecane zaktualizowanie uBO do `1.26.0`+ lub uBO Legacy `1.16.4.24`+.

W przypadku Nano Adblockera zalecana aktualizacja do wersji  `1.0.0.142`+

---

Dla starszych zrezygnowano z naprawy, zostaje komunikat zamknąć ręcznie lub akceptować go **skryptem dodatku** IDCAC.
