### ISSUE TITLE
gawex.pl

### ISSUE THREAD

**Issue by gzenio22** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#88]
Hej z tego co zauważyłem z pomocą ekipy polskich filtrów reklam coś od was z listy rozwala galerie zdjęć 

Tutaj:

![Screenshot_1](https://user-images.githubusercontent.com/21177361/100293448-146fec80-2f84-11eb-88b1-de2339c0a0c7.png) |
--- |

**Comment by krystian3w** [comment]
Strona czeka na wykonanie tego skryptu:

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/blob/7d672e79f89da8a4367326fa0f4b84288f2f533a/sections/adblock_cookies/ogolne_blokujace.txt#L18

Jak się nie ładuje to coś głupieje 🤔.

**Comment by gzenio22** [comment]
kombinujcie :) ja tu nie pomoge za wiele

**Comment by krystian3w** [comment]
Duplicate of https://github.com/MajkiIT/polish-ads-filter/issues/17840

**Comment by krystian3w** [comment]
Duplicate of https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/issues/2643
