### ISSUE TITLE
citybuzz.pl

### ISSUE THREAD

**Issue by xMaap** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#89]
![Zrzut ekranu z 2020-12-02 17-33-13](https://user-images.githubusercontent.com/36385327/100901812-8be1d680-34c4-11eb-9a7d-87f27e3f0e0c.png)

**Comment by krystian3w** [comment]
https://github.com/PolishFiltersTeam/PolishAnnoyanceFilters/commit/8207f651544ffaf9aada85a0e5e4b4ea45b674b8

a lista społecznościowa pewnie wytnie kilka dni później.
