### ISSUE TITLE
tme.eu/pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#90]
### Typ problemu
błąd
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Google Chrome 86.0.4240.75
### Dodatkowe informacje mogące mieć znaczenie
informacjo o rodo nie została zablokowana (automatycznie zaakceptowana) na stronie https://www.tme.eu/pl/

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by hawkeye116477** [comment]
> Może Bieda PC gargula.

Raczej to nie on, bo się nie podpisał. Sprawdziłem i to niby pracownik jakiejś pizzerii :smile:

**Comment by krystian3w** [comment]
A czyli pewnie ABP i trzeba by w opisie dodatku jeszcze mocnej podkreślić, że zalecamy wymianę na uBlock Origin / AdGuard.

Mnie komunikat miga pół sekundy, to jak Pizzerman nie znajdzie konfliktu pop-upów to ja nie widzę powodu akceptacji tego przez klikanie / `bakeCookie`.
