### ISSUE TITLE
allegro.pl

### ISSUE THREAD

**Issue by FadeMind** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#93]
![20210106-1609945966-001](https://user-images.githubusercontent.com/9846948/103784539-5d629880-503a-11eb-9d7a-b1258f7db8c2.png)

**Comment by hawkeye116477** [comment]
https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/commit/348e5cc1a48b58b1d28762e607c0603750e73031
