### ISSUE TITLE
open.fm

### ISSUE THREAD

**Issue by AroKol78** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#94]
lepsze usuniecie mediów społecznościowych (według mnie)
zauważyłem w "logger" że inne filtry przepuszczają
```
! open.fm media społecznościowe
||twitter.com^$all,domain=open.fm
||facebook.com^$all,domain=open.fm
||facebook.net^$all,domain=open.fm
open.fm##.social-btns
```

**Comment by AroKol78** [comment]
Cookies w nazwie mnie zmyliły
google ładnie wycięte to może inne korporacje
po co jakieś scrypty co tylk szpigują jak inne filtry wycinają tylko gadżety (część skryptów też - **nie wszystkie**)
`##.social-btns` na gadżety wystarczy

**Comment by hawkeye116477** [comment]
Ale zamieszałeś, nie wiem co dokładnie autor miał na myśli i czego oczekuje. Jednakże skrypty śledzące, to nie do nas, to jest lista ukrywająca widżety społecznościowe, a nie zajmująca się skryptami analitycznymi.

**Comment by AroKol78** [comment]
`https://majkiit.github.io/polish-ads-filter/` - Polskie Filtry Społecznościowe - wymagane easylist, polskie filtry, fanboy’s social

ubo legacy [myList](https://user-images.githubusercontent.com/70756447/102889523-1a5dce00-445b-11eb-9dfa-8919f5ae110c.PNG) +
"Polskie Filtry Elementów Irytujących - Scrollujące Filmiki"
"Fanboy’s Annoyance" 
"Fanboy’s Social"
"Polskie Filtry Społecznościowe DEV"
na tych filtrach już straciłem gadżety do mediów społecznościowych w polsatnews.pl gdzie oglądam transmisje na żywo
zbyt wiele filtrów, a i tak przepuszczają na `open.fm`
```
https://www.facebook.com/x/oauth/status?client_id=5.......
https://connect.facebook.net/pl_PL/all.js#xfbml=1......
https://syndication.twitter.com/settings
https://platform.twitter.com/widgets/widget_iframe.9.....
https://platform.twitter.com/widgets.js....
```

**Comment by hawkeye116477** [comment]
`a i tak przepuszczają na open.fm`

![2021-01-29_15-02](https://user-images.githubusercontent.com/19818572/106284160-1fc0ec00-6243-11eb-8960-d282649daa63.png)

**Comment by hawkeye116477** [comment]
@AroKol78 Nawet jest napisane, że może wywalić komentarze. Jednakże sam przecież chciałeś takie reguły. Nic lepszego nie znam, może @krystian3w poleci albo napisz do Fanboya prośbę o dodanie wyjątków dla paru stron.

**Comment by AroKol78** [comment]
lepsze usuniecie mediów społecznościowych z `open.fm` (tylko tyle chciałem)

**Comment by hawkeye116477** [comment]
W takim razie do filtrów własnych:
```
||facebook.com^$all,domain=open.fm
||facebook.net^$all,domain=open.fm
||twitter.com^$all,domain=open.fm
```

**Comment by krystian3w** [comment]
Widżety z zdjęciami/tekstami Twitter / FB / instagram mogą się pojawiać z artykułach niskich lotów:

https://open.fm/muzyka/ na chyba że masz własny crawler gdzie wykryłeś, że nie ma zdjęć/cytatów z socjalu.

**Comment by hawkeye116477** [comment]
Ah, no i tam znowu są komentarze, czyli jednak to potrzebne... Chociaż ja tą sekcję z artykułami Open FM widzę pierwszy raz w życiu.

**Comment by krystian3w** [comment]
Ja odkryłem około 6 stycznia.

@AroKol78  co za lista używa `$ghide` dla open.fm? Bo to jest generyk fanboya:

> `##.social-btns`

**Comment by krystian3w** [comment]
> Ah, no i tam znowu są komentarze, czyli jednak może to się przyda. 

Do wycięcia osadzonych multimedii z artykułów raczej nie, przecież na `naekranie.pl` przywracałeś osadzone posty z Twittera/FB.

A proponowany filtr kosmetyczny wymaga określenia popularności jak to nie słabość CPU sprawia, że XP nie używa jakiś filtrów generycznych.

**Comment by AroKol78** [comment]
> co za lista używa @@*$ghide

nie wiem , grzebałem na stronie i znalazłem,potem testowałam różne filtry https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/issues/94#issuecomment-769817227 i żaden nie spełnił oczekiwań
> A proponowany filtr kosmetyczny wymaga określenia popularności jak to nie słabość CPU sprawia, że XP nie używa jakiś filtrów generycznych.

bez problemu oglądam youtube 60hz

**Comment by krystian3w** [comment]
Czyli pewnie coś nie tak u Bogachenko i u niego "spadaj planszo anty-adblock 'na palmę bo mam babus'".
