### ISSUE TITLE
x-kom.pl

### ISSUE THREAD

**Issue by gwarser** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#96]
### Moja konfiguracja 
**Przeglądarka internetowa:** Firefox Nightly

**System operacyjny:** Manjaro

**Bloker:** uBO dev

**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
4. 
5. 

### Link bezpośredni (opcjonalny) 

`https://www.x-kom.pl/koszyk`

### Zrzut ekranu (opcjonalny) 

![image](https://user-images.githubusercontent.com/886325/108366541-c8d28500-71f8-11eb-912e-851732711cf0.png)

### Inne ważne informacje mogące mieć znaczenie (opcjonalne):

Ten psuje:

`x-kom.pl###app > div[class^="sc-"]:nth-of-type(1):style(height: 132px !important;)`

**Comment by seba2282** [comment]
Nie widzę ich. Może dlatego, że "I don't care about cookies"  robi swoje ?

**Comment by krystian3w** [comment]
IDCAC w wersji 3.2.7 robiło efekt białej strony:

https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/blob/2069911507e2a6af25045ac3276c909e1524685e/sections/adblock_cookies/bugi_kiboke.txt#L1 (pewnie filtr już można usunąć)

Wersja 3.2.8 skryptowo wycina zawartość koszyka (tego nie naprawimy listą do uBO, trzeba czekać na dodatek 3.2.9 z poprawkami).

**Comment by seba2282** [comment]
> IDCAC w wersji 3.2.7 robiło efekt białej strony:
> 
> https://github.com/PolishFiltersTeam/PolishSocialCookiesFiltersDev/blob/2069911507e2a6af25045ac3276c909e1524685e/sections/adblock_cookies/bugi_kiboke.txt#L1
> 
> (pewnie filtr już można usunąć)
> Wersja 3.2.8 skryptowo wycina zawartość koszyka (tego nie naprawimy listą do uBO, trzeba czekać na dodatek 3.2.9 z poprawkami).
> 
> Jak nie zmiksują jakieś dziwnej 3 wersji paska cookies to raczej już jest z filtrem `:style(` "OK".

Ale ja mam dodatek zainstalowany.
