### ISSUE TITLE
regioneo.pl

### ISSUE THREAD

**Issue by PolishJarvis** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#97]
### Moja konfiguracja 
**System operacyjny:** Windows
**Przeglądarka internetowa:** Waterfox Classic 56.5
**Bloker:** uBlock Origin 1.33.2
**Używane filtry:** 
1. EasyList
2. Oficjalne Polskie Filtry do AdBlocka, uBlocka Origin i AdGuarda
3. Polskie Filtry Elementów Irytujących
### Dodatkowe informacje mogące mieć znaczenie
blokada przewijania

Zgłoszenie opublikowane anonimowo przez użytkownika.

**Comment by krystian3w** [comment]
@kiboke bugged is `###cookie-law-info-again` and/or `###cookie-law-info-bar` for adblocker users.

**Comment by kiboke** [comment]
@krystian3w thank you, I'll fix it for regioneo.pl. All the other websites you suggested to recheck work fine on my side.
