### ISSUE TITLE
Drobne poprawki (propozycja) i pytania jak działają filtry?

### ISSUE THREAD

**Issue by blocker999** [PolishFiltersTeam/PolishSocialCookiesFiltersDev#99]
`lincoln.edu.pl,ustron.pl##a > .mdi-facebook.mdi` **do usunięcia, bo jest**
`pl##.mdi-facebook`

---

Filtr bazujący na proceduralnej ścieżce  (- błędne myślenie, że to duplikaty):

`conteshop.pl#?#.pl-lang-class.page > .page-line:-abp-has( > .title-instagramm1) + .list-gallery1` **to albo to**
 `conteshop.pl#?#.pl-lang-class.page > .page-line:-abp-has( > .title-instagramm1)`

`drtusz.pl#?#.infoBoxContents tr:has( > td > a[href*=".com/"][target]) + tr` **to albo to**
 `drtusz.pl#?#.infoBoxContents tr:has( > td > a[href*=".com/"][target])`

`pizzahut.pl#?#li.ph-footer-navigation-header:-abp-contains(ZNAJDŹ PIZZA HUT) ~ li.footer-icon` **to albo to**
 `pizzahut.pl#?#li.ph-footer-navigation-header:-abp-contains(ZNAJDŹ PIZZA HUT)`

`volcano.pl#?#section.section-text:-abp-contains(Znajdź nas w Social Media) + .section-banners` **to albo to**
 `volcano.pl#?#section.section-text:-abp-contains(Znajdź nas w Social Media)`

`yellowpages.pl#?#dl > dt:-abp-contains(Konta społecznościowe) + dd` **to albo to**
 `yellowpages.pl#?#dl > dt:-abp-contains(Konta społecznościowe)`

`radio.bialystok.pl#?#body > div:nth-of-type(15):-abp-has(h2:-abp-contains(/^(FACEBOOK|TWITTER)$/)) + div.row` **to albo to**
`radio.bialystok.pl#?#body > div:nth-of-type(15):-abp-has(h2:-abp-contains(/^(FACEBOOK|TWITTER)$/))`

`swietawdomu.pl#?#.elementor-inner-column.elementor-column > .elementor-column-wrap > .elementor-widget-wrap > .elementor-widget-heading.elementor-widget:-abp-contains(/^Twitter$/) + div + div` **to albo to** 
`swietawdomu.pl#?#.elementor-inner-column.elementor-column > .elementor-column-wrap > .elementor-widget-wrap > .elementor-widget-heading.elementor-widget:-abp-contains(/^Twitter$/)`

---

`tvn24bis.pl##.button_email`i `tvn24bis.pl#@#.button_email` **oba do usunięcia**

`miedzyrzecz.biz##.td-social-icon-wrap` i `alilove.pl,miedzyrzecz.biz#@#.td-social-icon-wrap`
**Pierwsza do usunięcia bo jest u fanbojów**

---

Filtry podobne:

`pl.wix.com##ul[aria-label="Pasek społecznościowy"]` **to albo to**
`~polnapol.com.pl##ul[aria-label="Pasek społecznościowy"], ul[aria-label="Social Bar"]`

---

Konflikt suplementu dla uBO/AG:

`um.kielce.pl##map > area[alt="Facebook"]:remove()` **to albo to**
 `um.kielce.pl##map > area[alt="Facebook"]:remove()`

---

Konfilikt umiejętności uBO a Adblock Plus:

`amicenergy.pl##.footer-contact.row > div[class]:nth-of-type(3) > *` **to albo to**
`amicenergy.pl##.footer-contact.row > div:nth-of-type(3)`

**Comment by krystian3w** [comment]
```
conteshop.pl#?#.pl-lang-class.page > .page-line:-abp-has( > .title-instagramm1) + .list-gallery1 to albo to
conteshop.pl#?#.pl-lang-class.page > .page-line:-abp-has( > .title-instagramm1)
```

Niestety oba drogi panie, to nie są równoważne filtry ani duplikat.

**Comment by krystian3w** [comment]
`##.td-social-icon-wrap` działa negatywnie usuwając RSS, więc trzeba by generować filtr oszczędzający button RSS.
